-- DISTRICTS
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('Ancón',1);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('Ate Vitarte',2);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('Barranco',3);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('Breña',4);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('Carabayllo',5);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('Chaclacayo',6);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('Chorrillos',7);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('Cieneguilla',8);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('Comas',9);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('El Agustino',10);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('Independencia',11);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('Jesús María',12);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('La Molina',13);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('La Victoria',14);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('Lima Cercado',15);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('Lince',16);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('Los Olivos',17);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('Lurigancho',18);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('Lurín',19);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('Magdalena del Mar',20);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('Miraflores',21);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('Pachacamac',22);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('Pucusana',23);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('Pueblo Libre',24);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('Puente Piedra',25);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('Punta Hermosa',26);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('Punta Negra',27);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('Rímac',28);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('San Bartolo',29);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('San Borja',30);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('San Isidro',31);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('San Juan de Lurigancho',32);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('San Juan de Miraflores',33);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('San Luis',34);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('San Martín de Porres',35);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('San Miguel',36);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('Santa Anita',37);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('Santa María del Mar',38);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('Santa Rosa',39);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('Santiago de Surco',40);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('Surquillo',41);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('Villa El Salvador',42);
INSERT INTO DISTRICTS (nameDistrict,idDistrict) VALUES ('Villa María del Triunfo',43);